DROP VIEW IF EXISTS STREAM_COUNT_BY_COUNTRY;
CREATE VIEW STREAM_COUNT_BY_COUNTRY(Country,StreamCount)
AS 
SELECT COUNTRY.Name, count(STREAM.StreamId) AS StreamCount FROM COUNTRY 
JOIN CUSTOMER ON (CUSTOMER.Country = COUNTRY.Name)
LEFT OUTER JOIN STREAM ON (STREAM.CustomerId = CUSTOMER.CustomerId)
group by COUNTRY.Name;